#!/bin/sh
### BEGIN INIT INFO
# Provides:          lattesAuthority
# Required-Start:    $network $remote_fs $local_fs 
# Required-Stop:     $network $remote_fs $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Stop/start lattesAuthority
### END INIT INFO

NAME=lattesAuthority
DAEMON=/usr/local/bin/${NAME}
USER=restpy
PIDFILE=/var/run/${NAME}.pid

. /lib/lsb/init-functions

start_service(){
	start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --user $USER --chuid $USER:$USER --startas $DAEMON
}

stop_service(){
	start-stop-daemon --stop --pidfile $PIDFILE --retry 10
}

case "$1" in
start)
	echo "Starting $NAME"
	start_service
	;;
stop)
	echo "Stopping $NAME"
	stop_service
	;;
restart)
	echo "Restarting $NAME"
	stop_service; start_service
	;;
*)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
	;;
esac

exit $?
